apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-env
  namespace: shared-infra
data:
  MATOMO_DATABASE_HOST: mariadb
  MATOMO_DATABASE_ADAPTER: mysql
  MATOMO_DATABASE_USERNAME: matomo
  MATOMO_DATABASE_PASSWORD: matomo
  MATOMO_DATABASE_DBNAME: matomo
  MATOMO_DATABASE_TABLES_PREFIX: matomo_
  # MATOMO_GENERAL_ENABLE_TRUSTED_HOST_CHECK: "0"   # Not Working, Don't know why
  # MATOMO_GENERAL_FORCE_SSL: "1"
  # MATOMO_PROXY_CLIENT_HEADER: "X-Forwarded-Proto: https"
  # MATOMO_HTTPS: "1"
  # global.ini.php: |
  #   [General]
  #   enable_trusted_host_check=0
  #   force_ssl=1
  #   trusted_hosts[] = "matomo.pingcap.net"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-pvc
  namespace: shared-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-deployment
  namespace: shared-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
        - name: matomo
          image: matomo:latest
          ports:
            - name: matomo
              containerPort: 80
          envFrom:
            - configMapRef:
                name: matomo-env
          volumeMounts:
            - mountPath: /var/www/html
              name: web-dir
      volumes:
        - name: web-dir
          persistentVolumeClaim:
            claimName: matomo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: matomo
  namespace: shared-infra
spec:
  selector:
    app: matomo
  ports:
    - name: http
      port: 80                                    # 内部集群访问Service的端口: Service将端口暴露在Cluster上, 集群内使用"ClusterIP:Port"可实现访问
      targetPort: 80                              # 后端Pod的服务端口: Pod将端口暴露的container上, 从port或nodePort进入的流量, 最终通过targetPort进入Pod中
      nodePort: 30790                             # 外部访问Service的端口: Service将端口暴露在Node上, 集群外使用"NodeIP:NodePort"可实现访问. --此值30000-32767范围可指定(不指定时随机分配)
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matomo
  namespace: shared-infra
spec:
  rules:
    - host: matomo.pingcap.net                    # 映射到该域名: 在系统的hosts文件里配置--将这个域名映射到nginx-ingress-controller的ip地址就可以访问
      http:                                       # 创建HTTP协议的访问
        paths:
          - path: /                               # 通过/路径就可以访问该服务(all paths match)
            pathType: Prefix                      # 以<path>分隔的URL路径前缀匹配,匹配对大小写敏感
            backend:                              # 后端service的名称及端口号
              service:
                name: matomo
                port:
                  number: 80
