apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-env
  namespace: shared-infra
data:
  MATOMO_DATABASE_HOST: mariadb
  MATOMO_DATABASE_ADAPTER: mysql
  MATOMO_DATABASE_USERNAME: matomo
  MATOMO_DATABASE_PASSWORD: matomo
  MATOMO_DATABASE_DBNAME: matomo
  MATOMO_DATABASE_TABLES_PREFIX: matomo_
  MATOMO_GENERAL_ENABLE_TRUSTED_HOST_CHECK: "0" # Not Working, Don't know why

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-pvc
  namespace: shared-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-deployment
  namespace: shared-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
        - name: matomo
          image: matomo:latest
          ports:
            - name: matomo
              containerPort: 80
          envFrom:
            - configMapRef:
                name: matomo-env
          volumeMounts:
            - mountPath: /var/www/html
              name: web-dir
      volumes:
        - name: web-dir
          persistentVolumeClaim:
            claimName: matomo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: matomo
  namespace: shared-infra
spec:
  selector:
    app: matomo
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30790
  type: NodePort
