apiVersion: v1
kind: Namespace
metadata:
  name: shared-infra

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: shared-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-pvc
  namespace: shared-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-config
  namespace: shared-infra
data:
  config.ini.php: |
    [General]
    trusted_hosts[] = "172.16.5.62:30780"
    enable_trusted_host_check=0

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: shared-infra
spec:
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: shared-infra
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: wfsoiosflkmcoisjaf
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: matomo
  namespace: shared-infra
spec:
  selector:
    app: matomo
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30780
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  namespace: shared-infra
spec:
  selector:
    matchLabels:
      app: matomo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
        - name: matomo
          image: matomo:latest
          env:
            - name: MATOMO_DATABASE_HOST
              value: mariadb
            - name: MATOMO_DATABASE_USER
              value: root
            - name: MATOMO_DATABASE_PASSWORD
              value: wfsoiosflkmcoisjaf
            - name: MATOMO_DATABASE_NAME
              value: matomo
            - name: MATOMO_DATABASE_PORT
              value: "3306"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: matomo-persistent-storage
              mountPath: /var/www/html
            - name: matomo-config
              mountPath: /path/to/matomo/config
      volumes:
        - name: matomo-persistent-storage
          persistentVolumeClaim:
            claimName: matomo-pvc
        - name: matomo-config
          configMap:
            name: matomo-config
            items:
              - key: config.ini.php
                path: config.ini.php
